---
- hosts: all
  tasks:
  - name: upload a file to the target if it doesnt exist
    copy:
	 src: /opt/program1.sh
	 dest: /home/ubuntu/program.sh
	 mode: 0755
  - name: if line not there then add it
    lineinfile:
	 state: present
	 dest: /home/ubuntu/program.sh
	 regexp: '^HOSTNAME='
	 line: HOSTNAME={{}ansible_hostname}
  - name: run the program
    shell: /home/ubuntu/program.sh
	register: program_output
  - debug: msg="stdout={{program_output}}"
  